version: "3"

services:
  keypoint_estimation:
    build: .
    ports:
      - 8090:8090
    volumes:
      - "../../scripts/keypoint_estimator/:/work/"
      - "~/sho/dataset/:/work/dataset/"
    tty: true
    stdin_open: true
