version: "3"

services:
  twostage:
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
      - "/workspace/sho/Git/:/work/"
    tty: true
    stdin_open: true
    deploy:
            resources:
                    reservations:
                            devices:
                                - driver: nvidia
                                  count: 1
                                  capabilities: [utility, compute, video, gpu]
